# Generated by Django 5.1.3 on 2025-07-05 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('relato', 'Relato'), ('noticia', 'Noticia'), ('estatistica', 'Estatistica'), ('projeto', 'Projeto')], default='vazio', max_length=11)),
                ('imagem_publicacao', models.ImageField(default='media/dama.png', upload_to='media')),
                ('status', models.CharField(choices=[('sub', 'Analise'), ('ok', 'Aprovada'), ('del', 'Deletada')], default='sub', max_length=8)),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Relato',
        ),
    ]
