# Generated by Django 5.1.3 on 2025-07-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publicacao_delete_relato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='imagem_publicacao',
            field=models.ImageField(blank=True, default='media/dama.png', null=True, upload_to='media'),
        ),
    ]
