# Generated by Django 5.1.3 on 2025-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_publicacao_imagem_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='imagem_publicacao',
            field=models.ImageField(blank=True, default='media/dama.png', null=True, upload_to='publicacoes'),
        ),
    ]
