# Generated by Django 5.1.3 on 2025-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_publicacao_imagem_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('municipio', models.CharField(max_length=100, unique=True)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('contato', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('policial', 'Policial'), ('medica', 'Medica'), ('juridica', 'Juridica')], default='policial', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
