name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependências
      - name: Install dependencies
        run: npm ci

      # Build para garantir que compila
      - name: Build Angular app
        run: npm run build -- --configuration production
